export { default as Cta } from "./cta";
export { default as Hero } from "./hero";
export { default as Header } from "./header";
export { default as Footer } from "./footer";
export { default as Product } from "./product";
export { default as Feature } from "./feature";
export { default as Statistics } from "./statistics";
export { default as CustomImage } from "./custom-image";
export { default as ShoppingCart } from "./shopping-cart";
